### PR TITLE
Scene_Sel instead of Scene_Load

### PR DESCRIPTION
**Pull request by jczwo**
My Yamaha definetly needs Scene_Sel.

### CODE REVIEW

**Comment by TommyCardello** [comment]
I agree with your changes on Scene_Sel.

But I am not sure about your changes to remove power off scene switch functionality.
I'll test it later today, but for now, I have some doubts.

When I developed this function, idea was to use a switch to turn on input (or scene) and being able to turn the receiver off using the same switch. If I need to change input, I press a different switch. When different switched has been turned off, previous switch will update status to Off.

The way you changed it, there might be a conflict. When you press scene switch off, it will do nothing. iOS Home app will turn it off, but in reality, nothing will happen. As a result, Home app will update switch status to ON.
Finally, you will have Scene 1 and Scene 2 (for example) both showing up as turned ON simultaneously.

That's exactly how homebridge-yamaha-scene plugin works. And I put some efforts to make switches status updating correctly.

**Comment by TommyCardello** [comment]
Okay,

I have tested everything.
Your changes make sense.

Scene_Sel works same as Scene_Load.
Hopefully, it will work for others.

Removing turnoff functionality from scene switch is not what I wanted to do, but I agree, it makes sense.

So, everything works fine. Pull can be merged.

**Comment by NorthernMan54** [comment]
Ok, I will publish this latest PR tonight

**Comment by NorthernMan54** [comment]
@jczwo @TommyCardello Thanks very much guys, I just published this.

**Comment by NorthernMan54** [comment]
@jczwo @TommyCardello I'm just trying this feature out and it works great, I'm using it to flip between tuner and spotify and is really useful.  My only comment was how the switches are handled, when I flip between the two, the switch stays "On" even when the mode is no longer active.  Would it make sense to flip the switch off, when another scene is selected?  Mind you this would only work correctly if you only used homebridge to control the receiver and not the remote itself.

**Comment by TommyCardello** [comment]
@NorthernMan54 Sure, I'll explain what I have found. 

1. GET method gets current input name and compares it to switch name in config.json. But Not the scene. Yamaha does not return current scene status. That's the reason why I strongly recommend to specify input in config.json when you add new scene switch. This way status will be updated correctly. Unless someone has a different solution.

2. The status will be updated but there is a delay. When you select different switch and previous stays on, you can force restart iOS app and previous switch status will be updated. 
I need to check why this delays happens. I use different plugin for turning on music on apple tv, and that switch updates instantly. 
I'll take a look how to avoid status update delay and if it's possible.

**Comment by NorthernMan54** [comment]
I’m just doing this

"inputs_as_accessories":{
        	"YamahaReceiver": {
          "1": {
                "name":"Radio",
                "setInputTo": "TUNER"
           },
          "2": {
                "name":"Spotify",
                "setInputTo": "Spotify"
           }
        }


I thinking just a simple state machine between the group of buttons, so if I turn on 1, it turns off the others.


PS If you name a button “Spotify” both Alexa and Siri treat is as a reserved word and turn on the native Spotify for each.

**Comment by TommyCardello** [comment]
I haven't tested it with anything other than HDMI and AUDIO inputs.
Yes, seems like the state machine will do the job. I've never done that, so I'll research for the solution.

I have checked code, which I mentioned above. That's homebridge-dacp plugin. They use a state machine for updating status. And that works flawlessly. Even when I pause the music using AppleTV remote, switch status in home app updates instantly. 
 I need to research how to do that. I'm still learning all this coding stuff :) 

Let me know if you have any ideas.

**Pull request merged**
